Multiset/force-app/main/default/objects/Acoes__c/Acoes__c.object-meta.xml
<CustomObject>
    <label>Ação</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Nome de Ações</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Multiset/force-app/main/default/objects/Acoes__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <label>Código</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Multiset/force-app/main/default/objects/Acoes__c/fields/Ult_Atualizacao__c.field-meta.xml
<CustomField>
    <fullName>Ult_Atualizacao__c</fullName>
    <label>Ultima Atualização</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

Multiset/force-app/main/default/classes/AtualizaAcoesBolsaValoresBatchable.cls
global class AtualizaAcoesBolsaValoresBatchable implements Database.Batchable<Acoes__c>,Database.AllowsCallouts {
    global Iterable<Acoes__c> start(Database.BatchableContext BC) {
        Datetime ultimos5Minutos = Datetime.now().addMinutes(-5);
        return [
            SELECT Stock__c
            FROM Acoes__c
            WHERE Ult_Atualizacao__c <=: ultimos5Minutos
        ];
    }
    global void execute(Database.BatchableContext bc, List<Acoes__c> scope) {
        AcoesBolsaValoresController controller = new AcoesBolsaValoresController();
        controller.atualizaAcoes(scope);
    }

    global void finish(Database.BatchableContext BC) {}
        
}