Multiset/force-app/main/default/objects/Acoes__c/Acoes__c.object-meta.xml
<CustomObject>
    <label>Ação</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Nome de Ações</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Multiset/force-app/main/default/objects/Acoes__c/fields/Change__c.field-meta.xml
<CustomField>
    <fullName>Change__c</fullName>
    <label>Variação</label>
    <precision>8</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Multiset/force-app/main/default/objects/Acoes__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Moeda</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Multiset/force-app/main/default/objects/Acoes__c/fields/High__c.field-meta.xml
<CustomField>
    <fullName>High__c</fullName>
    <label>Máxima</label>
    <precision>8</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Multiset/force-app/main/default/objects/Acoes__c/fields/Low__c.field-meta.xml
<CustomField>
    <fullName>Low__c</fullName>
    <label>Minima</label>
    <precision>8</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Multiset/force-app/main/default/objects/Acoes__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Preço</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Multiset/force-app/main/default/objects/Acoes__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <label>Código</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Multiset/force-app/main/default/objects/Acoes__c/fields/Ult_Atualizacao__c.field-meta.xml
<CustomField>
    <fullName>Ult_Atualizacao__c</fullName>
    <label>Ultima Atualização</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

Multiset/force-app/main/default/classes/AcoesBolsaValoresBatchableTest.cls
@isTest
public with sharing class AcoesBolsaValoresBatchableTest {
    @TestSetup
    static void makeData(){
        Acoes__c acao = new Acoes__c(
            URL__c = 'https://s3-symbol-logo.tradingview.com/brasileiro-petrobras--big.svg',
            Stock__c = 'PETR4',
            Price__c = 13.2,
            Change__c = 13.2,
            High__c = 13.2,
            Low__c = 13.2,
            Currency__c = 'BRL',
            Ult_Atualizacao__c = Datetime.now().addMinutes(-5)
        );
        insert acao;
    }

    @isTest
    static  void atualizarGarantiaAtivosTest(){
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new AcoesBolsaValoresMock());
        AtualizaAcoesBolsaValoresBatchable batch = new AtualizaAcoesBolsaValoresBatchable();
        Database.executeBatch( batch );
        Test.stopTest();
 }
    @isTest
    static void agendarBatchTest(){
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new AcoesBolsaValoresMock());
        AcoesBolsaValoresScheduler sch = new AcoesBolsaValoresScheduler();
        sch.execute(null);
        Test.stopTest();
    }
}