Multiset/force-app/main/default/objects/Acoes__c/Acoes__c.object-meta.xml
<CustomObject>
    <label>Ação</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Nome de Ações</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Multiset/force-app/main/default/objects/Acoes__c/fields/Change__c.field-meta.xml
<CustomField>
    <fullName>Change__c</fullName>
    <label>Variação</label>
    <precision>8</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Multiset/force-app/main/default/objects/Acoes__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Moeda</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Multiset/force-app/main/default/objects/Acoes__c/fields/High__c.field-meta.xml
<CustomField>
    <fullName>High__c</fullName>
    <label>Máxima</label>
    <precision>8</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Multiset/force-app/main/default/objects/Acoes__c/fields/Low__c.field-meta.xml
<CustomField>
    <fullName>Low__c</fullName>
    <label>Minima</label>
    <precision>8</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Multiset/force-app/main/default/objects/Acoes__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Preço</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Multiset/force-app/main/default/objects/Acoes__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <label>Código</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Multiset/force-app/main/default/objects/Acoes__c/fields/Ult_Atualizacao__c.field-meta.xml
<CustomField>
    <fullName>Ult_Atualizacao__c</fullName>
    <label>Ultima Atualização</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

Multiset/force-app/main/default/objects/AcoesUsuario__c/AcoesUsuario__c.object-meta.xml
<CustomObject>
    <label>Ação de Usuário</label>
    <nameField>
        <label>Nome de Ações de Usuário</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ações de Usuário</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Multiset/force-app/main/default/objects/AcoesUsuario__c/fields/Acao__c.field-meta.xml
<CustomField>
    <fullName>Acao__c</fullName>
    <label>Ação</label>
    <referenceTo>Acoes__c</referenceTo>
    <relationshipLabel>Ações de Usuário</relationshipLabel>
    <relationshipName>AcoesUsuario</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Multiset/force-app/main/default/objects/AcoesUsuario__c/fields/OwnerId__c.field-meta.xml
<CustomField>
    <fullName>OwnerId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Usuario</relationshipName>
    <type>Lookup</type>
</CustomField>

Multiset/force-app/main/default/classes/AcoesBolsaValoresLWCTest.cls
@isTest
public with sharing class AcoesBolsaValoresLWCTest {
    @TestSetup
    static void makeData(){
        List<Profile> idProfile = new List<Profile>([SELECT Id FROM Profile WHERE Name = 'Administrador do sistema' LIMIT 1]);
        User usuario = new User();
        usuario.alias = 'tdjsw123';
        usuario.LastName = 'testcoverage123';
        usuario.Email = 'teste12343@testcoverage.com.br';
        usuario.ProfileId = idProfile[0].Id;
        usuario.Username = 'teste123@testcoverage.com.br';
        usuario.TimeZoneSidKey = 'America/Sao_Paulo';
        usuario.LocaleSidKey = 'pt_BR';
        usuario.EmailEncodingKey = 'ISO-8859-1';
        usuario.LanguageLocaleKey = 'pt_BR';  
        insert usuario;

        Acoes__c acao = new Acoes__c(
            URL__c = 'https://s3-symbol-logo.tradingview.com/brasileiro-petrobras--big.svg',
            Stock__c = 'PETR4',
            Price__c = 13.2,
            Change__c = 13.2,
            High__c = 13.2,
            Low__c = 13.2,
            Currency__c = 'BRL',
            Ult_Atualizacao__c = Datetime.now().addMinutes(-5)
        );
        insert acao;

        insert new AcoesUsuario__c(
            Acao__c = acao.Id,
            OwnerId__c = UserInfo.getUserId()
        );
    }

    @isTest
    static void criaAcaoUsuario_exists_to_user_test() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new AcoesBolsaValoresMock());
        AcoesBolsaValoresLWC.criaAcaoUsuario('PETR4');
        Test.stopTest();
    }

    @isTest
    static void salvaAcaoUsuario_controller_test(){
        AcoesBolsaValoresController controller = new AcoesBolsaValoresController();
        controller.salvaAcaoUsuario(null);
    }

    @isTest
    static void criaAcaoUsuario_exception_test() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new AcoesBolsaValoresMock());
        AcoesBolsaValoresLWC.criaAcaoUsuario(null);
        Test.stopTest();
    }

    @isTest
    static void criaAcaoUsuario_not_exists_to_user_test() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new AcoesBolsaValoresMock());
        AcoesBolsaValoresLWC.criaAcaoUsuario('TSLA34');
        Test.stopTest();
    }

    @isTest
    static void criaAcaoUsuario_existent_acao_to_not_existent_user_test() {
        User usuario = [SELECT Id FROM User WHERE Email = 'teste12343@testcoverage.com.br' LIMIT 1];
        System.runAs(usuario) {
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new AcoesBolsaValoresMock());
            AcoesBolsaValoresLWC.criaAcaoUsuario('PETR4');
            Test.stopTest();
        }
    }

    @isTest
    static void criaAcaoUsuario_not_exists_test() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new AcoesBolsaValoresMock());
        AcoesBolsaValoresLWC.criaAcaoUsuario('INVALID');
        Test.stopTest();
    }

    @isTest
    static void getAcoes_test() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new AcoesBolsaValoresMock());
        String response = AcoesBolsaValoresLWC.getAcoes();

        Test.stopTest();
    }

    @isTest
    static void delAcao_test() {
        AcoesBolsaValoresLWC.delAcao('PETR4');
    }

    @isTest
    static void delAcao_exception_test() {
        AcoesBolsaValoresLWC.delAcao(null);
    }
    
    @isTest
    static void delAcao_not_existent_test() {
        AcoesBolsaValoresLWC.delAcao('INVALID');
    }

    @isTest
    static void delAcao_controller_test(){
        AcoesBolsaValoresController controller = new AcoesBolsaValoresController();
        controller.delAcao(null);
    }
}